### ISSUE TITLE
moving shapes dataset

### ISSUE THREAD

**Issue by HaziqRazali** [tfxue/visual-dynamics#1]
Hello, may I know where you got the moving shapes dataset from ? Did you generate it yourself ?

**Comment by HaziqRazali** [comment]
I already got a reply from the authors so closing this issue.

> 
To generate the moving shape dataset, we simply draw a few shapes on a solid-color background using Matlab's insertShape function. The location and speed of the shapes are randomly sampled from an uniform distribution.

**Comment by rohanrc1997** [comment]
Hello @HaziqRazali ,
It'd be very helpful if you could share the training code for the dataset.
Many thanks!
